server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: cop-platform
  
  datasource:
    url: jdbc:postgresql://localhost:5432/cop_platform
    username: ${DB_USERNAME:cop_user}
    password: ${DB_PASSWORD:cop_password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        format_sql: true
        
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: 86400000 # 24 hours

# MinIO Configuration
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET:cop-files}

# Logging
logging:
  level:
    com.cop: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
